require 'nokogiri'
require 'fileutils'

require_relative 'exception'
require_relative 'parser'
require 'nodes/node'
require 'nodes/nodeset'
require 'nodes/compound'
require 'nodes/member'
require 'nodes/class'
require 'nodes/enum'
require 'nodes/file'
require 'nodes/function'
require 'nodes/group'
require 'nodes/namespace'
require 'nodes/struct'
require 'nodes/variable'
