require 'rubygems'
require 'nokogiri'
require 'fileutils'

require 'parser'
require 'nodes/node'
require 'nodes/nodeset'
require 'nodes/class'
require 'nodes/file'
require 'nodes/function'
require 'nodes/group'
require 'nodes/namespace'
require 'nodes/struct'
require 'nodes/variable'
